package com.reservationsystem.placeholder;

/* Test code generated by Gemini */
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController // This tells Spring this class handles web requests
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @GetMapping("/") // This handles the "home" URL
    public String home() {
        return "Hello from Render!";
    }
}
/* End test code */

// import org.springframework.boot.SpringApplication;
// import org.springframework.boot.autoconfigure.SpringBootApplication;

// @SpringBootApplication
// public class PlaceholderApplication {

// 	public static void main(String[] args) {
// 		SpringApplication.run(PlaceholderApplication.class, args);
// 	}

// }
